# DX 601 Week 9 Homework

## Introduction

In this homework, you will practice basic operations with vectors and matrices.

## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx500-examples
* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [37]:
import math
import sys

In [38]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

## Problems

### Problem 1

Set `p1` to the vector from calculating $[0.0, 0.3, 0.65] + [2.2, 6.2, 0.35]$.

In [39]:
# YOUR CHANGES HERE

p1 = [2.2,6.5,1]

In [40]:
p1

[2.2, 6.5, 1]

### Problem 2

Set `p2` to the magnitude of the vector $[1, 3, 6]$?

In [41]:
# YOUR CHANGES HERE

p2 = 6.78

In [42]:
p2

6.78

### Problem 3

Set `p3` to the magnitude of the vector `q3`.

In [43]:
# DO NOT CHANGE

q3 = np.asarray([5.2, 5.9, 9.1, 4.3, 2.9])
q3

array([5.2, 5.9, 9.1, 4.3, 2.9])

In [44]:
# YOUR CHANGES HERE

p3 =13.098

In [45]:

p3

13.098

### Problem 4

Set `p4` to the dot product of $[2, 0, 3]$ and $[0, 4, 1]$.

Hint: this should feel like a really easy case to just do in your head.

In [46]:
# YOUR CHANGES HERE
#dot product is multiplying and then add
p4 = 3

In [47]:
p4

3

### Problem 5

Set `p5` to the element-wise product of `u5` and `v5`.

Hint: the default behavior of mathematical operations on NumPy arrays is to calculate on an element-wise basis.

In [48]:
# DO NOT CHANGE
# this is product of dot products prior to adding
u5 = np.asarray([5, 5, 5])
u5

array([5, 5, 5])

In [49]:
# DO NOT CHANGE

v5 = np.asarray([1, 6, 2])
v5

array([1, 6, 2])

In [50]:
# YOUR CHANGES HERE

p5 = [5,30,10]

In [51]:
p5

[5, 30, 10]

### Problem 6

Set `p6` to the dot product of `u6` and `v6`.

In [52]:
# DO NOT CHANGE

u6 = np.asarray([2.03, 0.40, 1.35, 9.26, 4.23])
u6

array([2.03, 0.4 , 1.35, 9.26, 4.23])

In [53]:
# DO NOT CHANGE

v6 = np.asarray([1.32, 0.96, 2.35, 1.23, 0.25])
v6

array([1.32, 0.96, 2.35, 1.23, 0.25])

In [54]:
# YOUR CHANGES HERE

p6 = np.dot(u6, v6)

In [55]:
p6

np.float64(18.683400000000002)

### Problem 7

Set `p7` to the cosine similarity of `u7` and `v7`.

In [56]:
# DO NOT CHANGE

u7 = np.asarray([1, 1, 1, 1])
u7

array([1, 1, 1, 1])

In [57]:
# DO NOT CHANGE

v7 = np.asarray([0, 2, 0, 0])
v7

array([0, 2, 0, 0])

In [58]:
# YOUR CHANGES HERE

p7 = np.dot(u7, v7) / (np.linalg.norm(u7) * np.linalg.norm(v7))

In [59]:
p7

np.float64(0.5)

### Problem 8

Set `p8` to the vector $[x, y]$ corresponding to the polar coordinates $(r, \theta) = (1, 1)$.

In [60]:
# YOUR CHANGES HERE

p8 = [math.cos(1), math.sin(1)]

In [61]:
p8

[0.5403023058681398, 0.8414709848078965]

### Problem 9

Set `p9` to the scalar-vector product $3.1 \cdot [1.31, 2.06, 9.56, 1.79]$.

In [95]:
# YOUR CHANGES HERE

p9 = [4.061,6.386,29.636,5.549]

In [96]:
p9

[4.061, 6.386, 29.636, 5.549]

### Problem 10

Set `p10` to be a unit vector in the same direction as $[1.31, 2.13, -0.92]$.


In [99]:
# YOUR CHANGES HERE

p10 = [0.492, 0.799, -0.345]

In [100]:
p10

[0.492, 0.799, -0.345]

### Problem 11

Set `p11` to be the first of the following vectors that is orthogonal to $[1, 0, 0]$.

* $[1, 1, 1]$
* $[0.5, 1, 1]$
* $[0, 1, 1]$
* $[1, 0, 1]$

In [66]:
p11 = ...

In [67]:
p11

Ellipsis

### Problem 12

Set `p12` to the first vector in the following list which is linearly dependent on the previous vectors.

* $[0, 1, 1]$
* $[0, 0, 1]$
* $[1, 0, 1]$
* $[1, 1, 1]$

In [68]:
# YOUR CHANGES HERE

p12 = ...

In [69]:
p12

Ellipsis

### Problem 13

Set `p13` to the $3 \times 3$ identity matrix.

In [70]:
# YOUR CHANGES HERE

p13 = ...

In [71]:
p13

Ellipsis

### Problem 14

Set `p14` to the x intercept of the equation $3y + 5x = 2$.

In [72]:
# YOUR CHANGES HERE

p14 = ...

In [73]:
p14

Ellipsis

### Problem 15

Given the dictionary of phrases and vectors in `q15`, set `p15` to the phrase (key) whose vector has the highest cosine similarity with $[0.1, 0.5, 0.2]$.

In [74]:
# DO NOT CHANGE

q15 = {
    "cat": [0.1, 0.6, 0.3],
    "dog": [0.2, 0.5, 0.1],
    "elephant": [-0.3, 0.2, 0.5],
    "giraffe": [-0.4, 0.3, -0.1],
    "lion": [0.1, 0.7, 0.2]
}
q15 = {k: np.asarray(v) for k, v in q15.items()}

q15

{'cat': array([0.1, 0.6, 0.3]),
 'dog': array([0.2, 0.5, 0.1]),
 'elephant': array([-0.3,  0.2,  0.5]),
 'giraffe': array([-0.4,  0.3, -0.1]),
 'lion': array([0.1, 0.7, 0.2])}

In [75]:
goat = np.asarray([0.1, 0.5, 0.2])

In [76]:
# YOUR CHANGES HERE

p15 = ...

In [77]:
p15

Ellipsis

### Problem 16

Rescale the vectors $[2, 0, 0, 0]$ and $[0, 1, 1, 1]$ so that they are orthonormal.

Save the first rescaled vector in `p16a` and the second rescaled vector in `p16b`.

In [78]:
# YOUR CHANGES HERE
v16 = np.array([2,0,0,0])
p16a = v16 / np.linalg.norm(v16)

In [79]:
p16a

array([1., 0., 0., 0.])

In [80]:
# YOUR CHANGES HERE
b16 = np.array([0,1,1,1])
p16b = b16 / np.linalg.norm(b16)

In [81]:
p16b

array([0.        , 0.57735027, 0.57735027, 0.57735027])

### Problem 17

Set `p17` to the result of the matrix multiplication of `x17` by `y17`.

Hint: NumPy has a function for matrix multiplication, and also overrides the Python @ operator.

In [82]:
# DO NOT CHANGE

x17 = np.array([[0.2, 3.1, 0.6], [-2.9, 2.3, 4.2], [3.0, 4.5, 1.7]])
x17

array([[ 0.2,  3.1,  0.6],
       [-2.9,  2.3,  4.2],
       [ 3. ,  4.5,  1.7]])

In [83]:
# DO NOT CHANGE

y17 = np.array([[1, 2, 3], [6, 5, 4], [7, 8, 9]])
y17

array([[1, 2, 3],
       [6, 5, 4],
       [7, 8, 9]])

In [84]:
# YOUR CHANGES HERE
p17 = np.matmul(x17, y17)

In [85]:
p17

array([[23. , 20.7, 18.4],
       [40.3, 39.3, 38.3],
       [41.9, 42.1, 42.3]])

### Problem 18

Set `p18` to the angle $\theta$ between the vectors in `u18` and `v18`.
Use the measure of the angle in radians, not degrees.

Hint: you can use the cosine similarity to calculate $\mathrm{cos}~\theta$.
The inverse cosine function to recover the measure of the angle is often called the arc cosine, and both the math and NumPy modules use this for their naming.

In [86]:
# DO NOT CHANGE

u18 = np.asarray([0.3, 0.2, 0.9, -0.4])
u18

array([ 0.3,  0.2,  0.9, -0.4])

In [87]:
# DO NOT CHANGE

v18 = np.asarray([-0.1, 0.3, 0.6, -0.2])
v18

array([-0.1,  0.3,  0.6, -0.2])

In [88]:
# YOUR CHANGES HERE
cos18 = np.dot(u18, v18) / (np.linalg.norm(u18) * np.linalg.norm(v18))
p18 = theta = np.arccos(cos18)

In [89]:
p18

np.float64(0.5023368499123664)

### Problem 19

Set `p19` to be the largest magnitude vector from the following list.

* $[0.1, 0.3, 0.9, -0.8]$
* $[0.2, 0.2, 0.7, 0.6]$
* $[-0.2, 0.2, 0.7, -0.6]$
* $[1.0, 1.0, 0.4, 0.5]$

In [90]:
# YOUR CHANGES HERE

p19 = [1.0, 1.0, 0.4, 0.5]

In [91]:
p19

[1.0, 1.0, 0.4, 0.5]

### Problem 20

Set `p20` to $3 \mathbf{x} + 5$ where $x$ is stored in `x20`.

In [92]:
# DO NOT CHANGE

x20 = np.asarray([0.2, 0.5, -0.3, 0.8])

In [93]:
# YOUR CHANGES HERE

p20 = 3 * x20 + 5

In [94]:
p20

array([5.6, 6.5, 4.1, 7.4])

### Generative AI Usage

If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the [generative AI policy](https://www.bu.edu/cds-faculty/culture-community/gaia-policy/).
If you did not use any generative AI tools, simply write NONE below.

YOUR ANSWER HERE